
version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home


volumes:
  jenkins-data:
    driver: local
